version: '3.2'
services:
  geth:
    container_name: private
    build:
      context: etc/chain/private/testnet
    image: xarcher/private-chain:lastest
    expose:
      - 8540
      - 8650
      - 30311
    command: sh start.sh
    logging:
      driver: "none"
    volumes:
    - type: volume
      source: chain_data
      target: /privateChain/node/geth
    networks:
      chain:
  deployer:
    container_name: deployer
    working_dir: /deployer/scripts
    build:
      context: ./
      dockerfile: scripts/Dockerfile
    image: xarcher/deployer:latest
    depends_on:
    - geth
    command:  ./998Deploy.sh private http://geth:8540
    networks:
      chain:
networks:
  chain:
volumes:
  chain_data: